apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}"
  labels:
    name: '{{ .Chart.Name }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      name: "{{  .Chart.Name }}"
  template:
    metadata:
      name: "{{  .Chart.Name }}"
      labels:
        name: "{{  .Chart.Name }}"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.containerServicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: DEBUG_MODE
            value : "{{ .Values.service.debugmode }}"