apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}"
  labels:
    name: "{{ .Chart.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:  
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.serviceTargetPort }}
  selector:
    name: "{{  .Chart.Name }}"
